"""empty message

Revision ID: 90c231461ef6
Revises: 38c4e85512a9
Create Date: 2022-03-15 16:12:54.458216

"""

# revision identifiers, used by Alembic.
revision = "90c231461ef6"
down_revision = "38c4e85512a9"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=64), nullable=True))
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=128), nullable=True)
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
