"""empty message

Revision ID: b28017ed02c1
Revises: 90c231461ef6
Create Date: 2022-03-16 08:54:10.165685

"""

# revision identifiers, used by Alembic.
revision = 'b28017ed02c1'
down_revision = '90c231461ef6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
